//
//  AuthorEntity.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import RealmSwift
import JASON

public protocol Authorable: class {

    var ID: Int { get set }
    var username: String { get set }
    var name: String { get set }
    var nickname: String { get set }
    var slug: String { get set }
    var URL: String { get set }
    var avatar: String { get set }
    var bio: String { get set }
    var registered: NSDate? { get set }
}

public class Author: Object, Authorable {
    
    public dynamic var ID = 0
    public dynamic var username = ""
    public dynamic var name = ""
    public dynamic var nickname = ""
    public dynamic var slug = ""
    public dynamic var URL = ""
    public dynamic var avatar = ""
    public dynamic var bio = ""
    public dynamic var registered: NSDate?
    
    public override static func primaryKey() -> String? {
        return "ID"
    }
    
    public override static func indexedProperties() -> [String] {
        return [
            "username",
            "slug"
        ]
    }
    
    public convenience init(json: JSON) {
        self.init()
        
        ID = json[.ID]
        username = json[.username]
        name = json[.name]
        nickname = json[.nickname]
        slug = json[.slug]
        URL = json[.URL]
        avatar = json[.avatar]
        bio = json[.description]
        registered = json[.registered]
    }
    
}