//
//  AuthorEntity.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import RealmSwift
import JASON

public class User: Object {
    
    public dynamic var id = 0
    public dynamic var username = ""
    public dynamic var name = ""
    public dynamic var email = ""
    public dynamic var link = ""
    public dynamic var content = ""
    
    public override static func primaryKey() -> String? {
        return "id"
    }
    
    public override static func indexedProperties() -> [String] {
        return [
            "username",
            "email"
        ]
    }
    
    public convenience init(json: JSON) {
        self.init()
        
        id = json[.id]
        username = json[.username]
        name = json[.name]
        email = json[.email]
        link = json[.link]
        content = json[.description]
    }
    
}
