//
//  AuthorEntity.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import RealmSwift
import JASON

public protocol Userable: class {

    var id: Int { get set }
    var username: String { get set }
    var name: String { get set }
    var email: String { get set }
    var content: String { get set }
    var url: String { get set }
    var slug: String { get set }
    var registered: NSDate? { get set }
    var avatar: String { get set }
    var isAdmin: Bool { get set }
}

public class User: Object, Userable {
    
    public dynamic var id = 0
    public dynamic var username = ""
    public dynamic var name = ""
    public dynamic var email = ""
    public dynamic var content = ""
    public dynamic var url = ""
    public dynamic var slug = ""
    public dynamic var registered: NSDate?
    public dynamic var avatar = ""
    public dynamic var isAdmin = false
    
    public override static func primaryKey() -> String? {
        return "id"
    }
    
    public override static func indexedProperties() -> [String] {
        return [
            "username",
            "email",
            "slug"
        ]
    }
    
    public convenience init(json: JSON) {
        self.init()
        
        id = json[.id]
        username = json[.username]
        name = json[.name]
        email = json[.email]
        content = json[.description]
        url = json[.url]
        slug = json[.slug]
        registered = json[.registered]
        avatar = json[.avatar]
        isAdmin = json[.isAdmin]
    }
    
}